swagger: '2.0'
info:
  version: '1.0.0'
host: localhost
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /login:
    post:
      description: Login by user
      operationId: login
      parameters:
        - name: user
          in: body
          description: User description
          required: true
          schema:
            $ref: '#/definitions/LoginUser'
      responses:
        200:
          description: User is logged in
        403:
          description: Wrong user
  /logout:
    get:
      description: Logout action
      operationId: logout
      responses:
        200:
          description: User is logged out
definitions:
  LoginUser:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
        format: email
      password:
        type: string
        format: password